# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Equipe"
url = "team"
weight = 2

[[main]]
name = "Projetos"
url = "projects"
weight = 3

[[main]]
name = "Publicações"
url = "research"
weight = 4

[[main]]
name = "Software"
url = "software"
weight = 5

[[main]]
name = "Aprendizado"
url = "learn"
weight = 6

[[main]]
name = "Contato"
url = "contact"
weight = 7


# footer menu left
[[footer_left]]
name = "Sobre"
url = "team"

[[footer_left]]
name = "Contato"
url = "contact"


# footer menu middle
[[footer_middle]]
name = "CADD"
url = "projects/#cadd"

[[footer_middle]]
name = "QM/MM"
url = "projects/#qmmm"

[[footer_middle]]
name = "Software"
url = "software"


# footer menu right
[[footer_right]]
name = "Professores"
url = "team/#profs"
weight = 1

[[footer_right]]
name = "Pós-Docs"
url = "team/#postphd"
weight = 2

[[footer_right]]
name = "Doutorado"
url = "team/#phd"
weight = 3

[[footer_right]]
name = "Mestrado"
url = "team/#msc"
weight = 4

[[footer_right]]
name = "Iniciação Científica"
url = "team/#ic"
weight = 5

[[footer_right]]
name = "Colaboradores"
url = "team/#colab"
weight = 6
