baseURL = "http://lmdm.biof.ufrj.br/newsite/"
languageCode = "pt-br"
title = "LMDM"
theme = "bigspring"
DefaultContentLanguage = "pt"
canonifyurls=true

[params]
    author = "Artur Duque Rossi"
    favicon = "/images/favicon.ico" # Path to favicon file
    custom_css = ["css/main.css"]
